### ISSUE TITLE
Do not notify watcher when watcher is PR author

### ISSUE THREAD

**Issue by aneeshusa** [servo/highfive#128]
See [servo/servo#11283](https://github.com/servo/servo/pull/11283) for an example.

File to change: `handlers/watchers/__init__.py`.
Add a test in the `handlers/watchers/tests` directory.

**Comment by nox** [comment]
What is that supposed to do? Notifications are just a comment, no?

**Comment by jdm** [comment]
Yes; don't include the PR author in the list of people notified.

**Comment by atelierJVA** [comment]
I would like to work in this one.

What I plan to do is:
- In `/handlers/watchers/__init__.py` check `user:{login:}` against watcher for a file/directory
- Add a new test, `new_pr_author_is_watcher.json` with `test_user`as the PR author; I assume that a file/directory will only have 1 watcher, otherwise some tests would fail.
- Modify the existing test to include the :user and :login in the payload; should I rename it to `new_pr_author_not_a_watcher.json`?)

is this correct?

**Comment by jdm** [comment]
Those steps sound correct!

**Comment by Wafflespeanut** [comment]
fixed by #138
