### ISSUE TITLE
Support wildcard paths in file-watching

### ISSUE THREAD

**Issue by jdm** [servo/highfive#195]
We support notifying users when specific files or paths are modified in new PRs. It would be nice to support wildcard paths like "components/script/dom/*worklet*.rs", which requires using [fnmatch](https://docs.python.org/2/library/fnmatch.html) instead of `startswith`.

Code: https://github.com/servo/highfive/blob/master/handlers/watchers/__init__.py#L42 and https://github.com/servo/highfive/blob/master/handlers/watchers/__init__.py#L46
Add a test to https://github.com/servo/highfive/blob/master/handlers/watchers/tests, and run it with `python test.py`.

**Comment by s-moffett** [comment]
I'd be happy to take a stab at this. It'll be my first involvement with Mozilla.

@highfive : assign me

**Comment by jdm** [comment]
Great! Please ask questions about anything that's unclear!

**Comment by s-moffett** [comment]
Thanks for the welcome!

It looks like there might be a design decision to make here. As `fnmatch` requires wildcard characters for non-exact comparison, simply switching to `fnmatch` will break the current rules. For example, the rule `/watched/dir/` won't be triggered when `/watched/dir/file.rs` is added, but the rule `/watched/dir/*` will.

I went ahead and added wildcards to `watchers.ini` for testing, but this will require users to use wildcards in the future.

Our options are:
a) simply switch to `fnmatch` and require users to use wildcards such as `/watched/dir/*` or
b) add code that adds `*` to paths that look like directories rather than files.

**Comment by jdm** [comment]
Good point! While it's tempting to silently add *s, I think it will be too easy to overlook new additions that forget a trailing /. Therefore I think making the wildcards for directories explicit makes the most sense.

**Comment by s-moffett** [comment]
Great! I just sent over a PR. #198

**Comment by tigercosmos** [comment]
should this close?

**Comment by KiChjang** [comment]
Yes.
