### ISSUE TITLE
Provide APIs for iterating over the filenames in a diff, the file contents, and determining if a file is being added/removed

### ISSUE THREAD

**Issue by jdm** [servo/highfive#47]
Instead of multiple handlers reimplementing the same diff parsing code, we should allow them to express what they're actually trying to do.

**Comment by jdm** [comment]
These APIs would be defined in eventhandler.py, and could replace code in handlers/missing_test/ and handlers/unsafe/.

**Comment by jdm** [comment]
This could also be used in the handler introduced in #46.

**Comment by numberMumbler** [comment]
i'll start working on this one if it's still needed

**Comment by jdm** [comment]
Please do!

**Comment by jdm** [comment]
@numberMumbler Any progress here?

**Comment by numberMumbler** [comment]
@jdm the refactoring was pretty straightforward, but I got side tracked on related issue:

i updated the logic in the _watchers_ handler that gets the files from the diff header (originally at line 26 in `watchers/__init__.py`) so that it can work more generally. But, that's causing 6  of the _missing_test_ handler's tests to fail, because the _watcher_'s comments now show up during the _missing_test_ handler's tests (so there's an extra comment). I've been poking around the test runner (`test.py`) trying to see what's going on

Should I just put the other changes in a PR so we can move forward? Or better to keep plugging away at this?

**Comment by jdm** [comment]
So it's a known issue that the handlers aren't tested in isolation. If there's a way to solve that, that would be a great improvement. Without seeing the code, can we not just change some of the test data so that the files in question don't overlap?

**Comment by numberMumbler** [comment]
:+1: might take me another week or so... end of the semester, and all

**Comment by jdm** [comment]
Thanks for letting us know!

**Comment by numberMumbler** [comment]
@jdm are the entries in_ handlers/watchers/watchers.ini_ production values? Or, are they just examples?

My schedule has some slack in it again, so diving back into this

**Comment by jdm** [comment]
Those are production values.
