### ISSUE TITLE
Remove `s-awaiting-merge` label once issues are merged

### ISSUE THREAD

**Issue by edunham** [servo/highfive#77]
It's cluttery and confusing when examining a repo's closed issues.

**Comment by Mylainos** [comment]
I would like to do this one !

**Comment by jdm** [comment]
You're welcome to it!

**Comment by Mylainos** [comment]
We want to remove the label when the pull request is closed or merged or both ? Do we want to remove more labels ?

**Comment by Mylainos** [comment]
Is there others payload actions than opened synchronize and created ? Because I think we can use `merge_at` of the synchronize action : https://github.com/servo/highfive/blob/master/handlers/status_update/tests/synchronize.json#L46.

If we add `on_pr_closed`, synchronize will have 2 events (here https://github.com/servo/highfive/blob/master/eventhandler.py#L8) witch will call the same function in `status_update`.

**Comment by jdm** [comment]
Fixed by #78.
